// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package pay_test
//
// Package pay_test is a generated GoMock package.
package pay_test

import (
	context "context"
	reflect "reflect"

	model "github.com/tiptop-co/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockpaymentRepo is a mock of paymentRepo interface.
type MockpaymentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockpaymentRepoMockRecorder
}

// MockpaymentRepoMockRecorder is the mock recorder for MockpaymentRepo.
type MockpaymentRepoMockRecorder struct {
	mock *MockpaymentRepo
}

// NewMockpaymentRepo creates a new mock instance.
func NewMockpaymentRepo(ctrl *gomock.Controller) *MockpaymentRepo {
	mock := &MockpaymentRepo{ctrl: ctrl}
	mock.recorder = &MockpaymentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpaymentRepo) EXPECT() *MockpaymentRepoMockRecorder {
	return m.recorder
}

// UpdateStatus mocks base method.
func (m *MockpaymentRepo) UpdateStatus(ctx context.Context, paymentID int64, status model.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, paymentID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockpaymentRepoMockRecorder) UpdateStatus(ctx, paymentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockpaymentRepo)(nil).UpdateStatus), ctx, paymentID, status)
}
